# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout cc65
        uses: actions/checkout@v2
        with:
          repository: cc65/cc65
          path: cc65

      - name: Checkout orix-sdk
        uses: actions/checkout@v2
        with:
          repository: assinie/orix-sdk
          path: orix-sdk

      - name: Compilation CC65
        run: make -C cc65 >/dev/null

      - name: Préparation environnement pour orix-sdk
        run: |
          git clone --no-checkout --depth 1 --single-branch --branch master https://github.com/orix-software/shell orix-software/shell
          cd orix-software/shell
          git config --local core.sparseCheckout true
          echo "src/include" >> .git/info/sparse-checkout
          git checkout
          cd ../..
          git clone --no-checkout --depth 1 --single-branch --branch master https://github.com/orix-software/kernel orix-software/kernel
          cd orix-software/kernel
          git config --local core.sparseCheckout true
          echo "src/include" >> .git/info/sparse-checkout
          git checkout

      - name: Compilation orix-sdk
        working-directory: orix-sdk
        run: mkdir -p build/{lib,bin} && CC65_HOME=${GITHUB_WORKSPACE}/cc65 make lib

      - name: Vérification (1)
        run: |
          ls -lR orix-sdk
          ls -l cc65/bin
          PATH=$PATH:${GITHUB_WORKSPACE}/cc65/bin
          echo $PATH
          cc65 -V

      - name: Préparation environnement pour le projet
        run: mv cc65 ../ && mv orix-software ../ && mv orix-sdk ../

      - name: Compilation du projet
        run: CC65_HOME=${GITHUB_WORKSPACE}/../cc65 make

      - name: Vérification (2)
        run: ls -lR build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/bin

      - name: Post compilation
        run: mv ../cc65 . && mv ../orix-software . && mv ../orix-sdk .
